In [2]:
# steps in data analysis and data science
# get information about the bussiness or the organization
# know the problem
# getting the right data
#exploratory data analysis (EDA)
    # data cleaning
    # data transformation
    # descriptive analysis (python, powerbi, tableau)
    # data visualization (python, powerbi, tableau)
# machine learning (python) (linear regression, binary classificatiion, multi classification, clustering, text or sentiment analysis)
    # preprocessing
    # model building
    # evaluation (verification)
    # model development
# deep learniung

# modules

In [2]:
# numpy : numerical python
import numpy as np
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_ms

In [4]:
# one dimensional array
arr1 = np.array([75,85,60,47])
arr1

array([75, 85, 60, 47])

In [5]:
arr1.ndim # checking the numbers of array dimention

1

In [6]:
arr1.shape # checking the shape of the array, it could be two dimentional as a metrix or one dimensional 

(4,)

In [7]:
arr1.dtype # checking the data type of the array

dtype('int32')

In [10]:
# two dimensional array
arr2 = np.array([[47,85,69,60],[80,85,64,90]])
arr2

array([[47, 85, 69, 60],
       [80, 85, 64, 90]])

In [11]:
arr2.ndim

2

In [12]:
arr2.shape

(2, 4)

In [14]:
arr2.dtype

dtype('int32')

In [15]:
# to create an array where all values are zero
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [16]:
# to make it in 4 rows and 5 columns
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
# to create an array where all values are one
np.ones(60)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
# to create an array where all values are any other number aside zero or one 
np.ones(50) * 15

array([15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
       15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
       15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.,
       15., 15., 15., 15., 15., 15., 15., 15., 15., 15., 15.])

In [20]:
np.ones((5,5)) *  15

array([[15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15.]])

In [21]:
# linspace: generating an array that are evenly space but the condition is you must set the interval
np.linspace(20,90)

array([20.        , 21.42857143, 22.85714286, 24.28571429, 25.71428571,
       27.14285714, 28.57142857, 30.        , 31.42857143, 32.85714286,
       34.28571429, 35.71428571, 37.14285714, 38.57142857, 40.        ,
       41.42857143, 42.85714286, 44.28571429, 45.71428571, 47.14285714,
       48.57142857, 50.        , 51.42857143, 52.85714286, 54.28571429,
       55.71428571, 57.14285714, 58.57142857, 60.        , 61.42857143,
       62.85714286, 64.28571429, 65.71428571, 67.14285714, 68.57142857,
       70.        , 71.42857143, 72.85714286, 74.28571429, 75.71428571,
       77.14285714, 78.57142857, 80.        , 81.42857143, 82.85714286,
       84.28571429, 85.71428571, 87.14285714, 88.57142857, 90.        ])

In [22]:
# eye: create a two dimestional array having zero elsewhere and ones in diagonal
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [23]:
# arange (array range) to generate some numbers
arr4 = np.arange(1,101)
arr4

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [25]:
# to create an array based on specified interval (interval of 5)
arr4 = np.arange(1,101,5) 
arr4

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [26]:
# to generate any random numbers: start from 15, stop at 105 and the total number is 100
arr5 = np.random.randint(15,105,100)
arr5

array([ 15,  89, 103,  25,  80,  82,  76,  92,  43,  17,  20,  55, 104,
        79,  33,  50,  53, 104, 104,  54,  15,  25,  37,  71,  41,  91,
       101,  84,  77,  97,  50,  27,  61,  27,  43,  94,  84,  48,  27,
        84,  70,  36,  81,  88,  33,  60,  92, 102,  33, 104,  16,  57,
       100,  75,  77,  49,  72,  64,  18, 103,  56,  95,  42, 100,  56,
        16,  69,  24,  98,  42,  99,  20,  98,  46,  84,  62,  43,  69,
        49,  52,  89,  67,  36,  96,  66,  47,  25,  81,  60,  97,  56,
        24,  95,  59,  66,  28,  33,  83,  50,  99])

In [27]:
# seed: helps everybody to have the same randon number
np.random.seed(5)
arr5 = np.random.randint(15,105,100)
arr5

array([ 93,  76,  31,  88,  23,  77,  42,  45,  95,  22,  91,  30,  68,
        95,  42,  59,  92,  90,  80,  62,  45,  99, 101,  33,  24,  56,
        77,  16,  97,  31,  93,  20,  73,  15,  95,  19,  51,  66,  42,
        46,  17,  83,  53,  98,  34,  33,  22,  45,  77,  26,  82,  80,
        70,  18,  93,  42,  44,  48, 104, 100,  22,  31,  29,  46,  24,
        53,  62,  31,  20,  49,  60,  74,  39,  28,  46,  47,  91,  59,
        20,  29,  62,  97,  15,  22, 101,  31,  79,  23,  59,  52,  90,
        20,  37,  67,  84,  97,  75,  44, 103,  94])

In [28]:
# to convert one dimension array to two dimension array
arr6 = arr5.reshape(10,10)
arr6

array([[ 93,  76,  31,  88,  23,  77,  42,  45,  95,  22],
       [ 91,  30,  68,  95,  42,  59,  92,  90,  80,  62],
       [ 45,  99, 101,  33,  24,  56,  77,  16,  97,  31],
       [ 93,  20,  73,  15,  95,  19,  51,  66,  42,  46],
       [ 17,  83,  53,  98,  34,  33,  22,  45,  77,  26],
       [ 82,  80,  70,  18,  93,  42,  44,  48, 104, 100],
       [ 22,  31,  29,  46,  24,  53,  62,  31,  20,  49],
       [ 60,  74,  39,  28,  46,  47,  91,  59,  20,  29],
       [ 62,  97,  15,  22, 101,  31,  79,  23,  59,  52],
       [ 90,  20,  37,  67,  84,  97,  75,  44, 103,  94]])

In [29]:
# selecting values from 2d array
# to select a particular value: you must know the row and column: remember to count from 0
# select the value in row 4, column 5
arr6[4,5]

33

In [30]:
# selecting more than one values from 2d array e.g
# select row 3 to row 6 and column 3 to column 5
arr6[3:7,3:6]

array([[15, 95, 19],
       [98, 34, 33],
       [18, 93, 42],
       [46, 24, 53]])

In [31]:
# broadcasting: applying a value in a selected value
arr6[3:7,3:6] = 100
arr6

array([[ 93,  76,  31,  88,  23,  77,  42,  45,  95,  22],
       [ 91,  30,  68,  95,  42,  59,  92,  90,  80,  62],
       [ 45,  99, 101,  33,  24,  56,  77,  16,  97,  31],
       [ 93,  20,  73, 100, 100, 100,  51,  66,  42,  46],
       [ 17,  83,  53, 100, 100, 100,  22,  45,  77,  26],
       [ 82,  80,  70, 100, 100, 100,  44,  48, 104, 100],
       [ 22,  31,  29, 100, 100, 100,  62,  31,  20,  49],
       [ 60,  74,  39,  28,  46,  47,  91,  59,  20,  29],
       [ 62,  97,  15,  22, 101,  31,  79,  23,  59,  52],
       [ 90,  20,  37,  67,  84,  97,  75,  44, 103,  94]])

In [32]:
# to convert 2d back to 1d
arr7 = arr6.flatten()
arr7

array([ 93,  76,  31,  88,  23,  77,  42,  45,  95,  22,  91,  30,  68,
        95,  42,  59,  92,  90,  80,  62,  45,  99, 101,  33,  24,  56,
        77,  16,  97,  31,  93,  20,  73, 100, 100, 100,  51,  66,  42,
        46,  17,  83,  53, 100, 100, 100,  22,  45,  77,  26,  82,  80,
        70, 100, 100, 100,  44,  48, 104, 100,  22,  31,  29, 100, 100,
       100,  62,  31,  20,  49,  60,  74,  39,  28,  46,  47,  91,  59,
        20,  29,  62,  97,  15,  22, 101,  31,  79,  23,  59,  52,  90,
        20,  37,  67,  84,  97,  75,  44, 103,  94])

In [33]:
# to know the sum of the array
np.sum(arr7)

6311

In [35]:
np.max(arr7)

104

In [36]:
np.min(arr7)

15

In [37]:
np.mean(arr7)

63.11

In [42]:
# to check a particular % of the total
# check the 50 % of arr7
np.percentile(arr7,50)

62.0

In [41]:
# to check the location of the first maximum value
np.argmax(arr7)

58

In [1]:
# to understand data analysis and vitualization, read
domain knowledge
communication skills
problem-solving and critical thinking
collaboration and teamwork
ethics and data privacy
project management
bussiness acumen
adaptability and continous learning
the art of communication
tailoring communication to your audience
persuasive communication
mastering visualization tools
choosing the right visuals
design principles
data storytelling and context
emotional intelligence in communication
visual story telling
using dashboard effectively
colour management
infographic and interactive reports
simplifying complex data
use of analogies and metaphors
speaking the language of business
collaborative tools
visualization ethics
avaoiding misleading graphs
transperency
learning from feedback
continuos improvment

# to understand data science, read
descriptive statistics
inferential statistics
probability distribution
central limit theorem
hypothesis testing
p-values and significance levels
confidence intervals
correlation and causation
regression analysis
sampling method
bias and variance
outliers and thier impacts
t-tests and z-tests
anova (analysis of variance)
data normalization

SyntaxError: invalid syntax (3818865865.py, line 2)